### ISSUE TITLE
In iOS 13.0, the Setting app crashes when trying to open license page

### ISSUE THREAD

**Issue by OlKir** [mono0926/LicensePlist#105]
The same configuration shows list of licenses as expected for iOS 12, but the list is empty in iOS 13 Beta 5.

After a couple of experiments I found that items on the second level of Settings.bundle appear only if they are "wrapped" into PSGroupSpecifier.

So beginning of the com.mono0926.LicensePlist should look like:
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>PreferenceSpecifiers</key>
	<array>
		<dict>
			<key>Type</key>
			<string>PSGroupSpecifier</string>
			<key>Title</key>
			<string></string>
			<key>Footer</key>
			<string></string>
		</dict>
		<dict>
			<key>File</key>
			<string>com.mono0926.LicensePlist/Alamofire</string>
			<key>Title</key>
			<string>Alamofire</string>
			<key>Type</key>
			<string>PSChildPaneSpecifier</string>
		</dict>
```

**Comment by mono0926** [comment]
Thanks for reporting the issue.
On beta 6, it starts crashing 🤔
I’ll take action in a while.

**Comment by mono0926** [comment]
It seems to be fixed on iOS 13.1 beta 1, released yesterday without any code changes 🤔

**Comment by 417-72KI** [comment]
[FYI]
I tried in iOS13GM Seed, then crashing happened again😂

**Comment by mono0926** [comment]
@417-72KI 
Thank you for the information.

There are no problems on iOS 13.1 beta 3, so it seems to be the problem on iOS 13.0 only 🤔

**Comment by sidepelican** [comment]
On iOS 13.1 Beta 4 (17A5844a), Crashes when swipe back from license detail page 😅

**Comment by cruisediary** [comment]
On iOS 13.1 (17A5844) has same issue 😢

**Comment by shadowsheep1** [comment]
Issue still present in iOS 13.1.1

**Comment by mono0926** [comment]
[I've released this as 2.7.1 👍 ](https://github.com/mono0926/LicensePlist/releases/tag/2.7.1).
Thanks to @roana0229 .

**Comment by andlang** [comment]
This issue exists again with 2.9.0 and iOS 13.2.2

**Comment by BastiaanAndriessen** [comment]
Also experiencing a crash with iOS 13.2.2. Posted another issue: https://github.com/mono0926/LicensePlist/issues/123
