### ISSUE TITLE
Support for Swift Package Manager

### ISSUE THREAD

**Issue by mbuchetics** [mono0926/LicensePlist#107]
Great tool, thank you. We are using Carthage as our dependency manager but are planning on migrating all projects to Swift Package Manager soon. Is there any support planned?

**Comment by mono0926** [comment]
Thanks 👍 

[LicensePlist already supported SwiftPM(Swift Package Manager)](https://github.com/mono0926/LicensePlist/blob/master/Package.swift), but it is used for development, not distribution.

LicensePlist is command line tools not Framework embedded in apps, so current recommended distribution method is [CocoaPods as written here](https://github.com/mono0926/LicensePlist#cocoapods-recommended).

CocoaPods supports Binaries Distribution but [SwiftPM doesn't support it](https://forums.swift.org/t/spm-support-for-binaries-distribution/25549), so LicensePlist cannot be distributed via SwiftPM.

If SwiftPM supports Binaries Distribution, I'll consider to supports it.

**Comment by mbuchetics** [comment]
Sorry, I didn't make myself clear. I wasn't talking about SPM Support for LicensePlist itself but parsing the ´Package.swift´ file from a project to generate the list of used dependencies and frameworks (similar to parsing the ´Cartfile´ or ´Podfile´). Or is that already working as well?

**Comment by mono0926** [comment]
Oh, I’ve figured out.
Indeed, it is important, I’ll consider to support SwiftPM.

Of course, PR is welcome 😁

**Comment by mbuchetics** [comment]
Working on it!

**Comment by mbuchetics** [comment]
https://github.com/mono0926/LicensePlist/pull/108

**Comment by mono0926** [comment]
@mbuchetics 

Thank you for the PR!!
[I've released it as 2.6.0](https://github.com/mono0926/LicensePlist/releases/tag/2.6.0) 👍
