### ISSUE TITLE
The settings app crashes when navigating back from a license page (iOS13.2.2, LicencePlist v2.9)

### ISSUE THREAD

**Issue by BastiaanAndriessen** [mono0926/LicensePlist#123]
In iOS 13.2.2, the Setting app crashes when navigating back from a license page.
[The generated plist](https://drive.google.com/open?id=19uy4GOb76k2xsoXlH-7GEpC3luSP85JX)
[Crash video](https://drive.google.com/open?id=1nf107nw1yy0SpENpIM3xUeOzA-owOOza)
I am using LicencePlist v2.9.

As reported in [the other issue](https://github.com/mono0926/LicensePlist/issues/105), the Settings app also crashes on iOS 13.0, and does so immediately after selecting "Acknowledgements" (not after navigating back from a license). Remarkably, I don't have any issues on iOS 13.1 (also no popping and pushing when selecting a single library).

After playing around with the plist properties I found out that removing the Title property of the PSGroupSpecifier in the generated plist fixes the crash, but produces
[this behavior](https://drive.google.com/open?id=1MrtbMm4GtirUIOhrf4VKW1L0PW1dVPg7).
I've seen this behavior within the acknowledgement section of other apps (p.e. Github and Asana).

My guess is this is caused by iOS, but it would be nice to avoid generating the title until Apple releases a fix.

**Comment by griffin-stewie** [comment]
Same here.

As a workaround, It won't be crashed and won't produce [weird behavior](https://drive.google.com/open?id=1MrtbMm4GtirUIOhrf4VKW1L0PW1dVPg7) if you have 2 levels navigations stacks.

@mono0926 
We don't have to worry about these kind of Settings.app's bugs if we have #120 gets merged.

**Comment by mono0926** [comment]
Released [2.10.0](https://github.com/mono0926/LicensePlist/releases/tag/2.10.0), which supports `--single-page` option.

You can use this option to avoid this kind of bug for now :dog:

**Comment by BastiaanAndriessen** [comment]
Thank you so much!

**Comment by griffin-stewie** [comment]
@mono0926 @BastiaanAndriessen @NewFieldForMe 
Thank you guys!

**Comment by Patchivic** [comment]
Solved with 13.3 update today.
