### ISSUE TITLE
Incorrect name of repo from SPM inside Xcode

### ISSUE THREAD

**Issue by schjonhaug** [mono0926/LicensePlist#136]
We're using https://github.com/Iterable/swift-sdk in our project, and it was added in Xcode. However, it gets displayed as "swift-sdk" and not the expected IterableSDK:

<img width="557" alt="Skjermbilde 2020-07-02 kl  13 08 14" src="https://user-images.githubusercontent.com/84225/86352262-cd482e80-bc65-11ea-8bdc-d17433bddec9.png">

Looking at https://github.com/Iterable/swift-sdk/blob/master/Package.swift, can it be that LicensePlist is using "path" instead of "name"?

**Comment by schjonhaug** [comment]
If it helps, here's my Package.resolved file:

```
{
  "object": {
    "pins": [
      {
        "package": "Amplitude",
        "repositoryURL": "https://github.com/amplitude/Amplitude-iOS",
        "state": {
          "branch": null,
          "revision": "7c5966203d18ce78d9f4bcb9ac46acda4f395b2c",
          "version": "5.2.0"
        }
      },
      {
        "package": "Lottie",
        "repositoryURL": "https://github.com/airbnb/lottie-ios",
        "state": {
          "branch": null,
          "revision": "4e5877425dae5c10792fc9d22d53dc6bf6824dc1",
          "version": "3.1.8"
        }
      },
      {
        "package": "IterableSDK",
        "repositoryURL": "https://github.com/Iterable/swift-sdk",
        "state": {
          "branch": null,
          "revision": "63cb7db7623775626c5d10c1340333825e369ac6",
          "version": "6.2.8"
        }
      }
    ]
  },
  "version": 1
}

```

**Comment by mono0926** [comment]
@schjonhaug 

Thanks for the report 👍 
I fixed the problem and released 🚀
https://github.com/mono0926/LicensePlist/releases/tag/2.16.0

Could you close the issue if you confirmed the fix.

**Comment by schjonhaug** [comment]
Seems to be working fine, thanks!
