### ISSUE TITLE
Mapbox license not visible

### ISSUE THREAD

**Issue by illabo** [mono0926/LicensePlist#138]
Hello there!

On older iOS versions (tried on iOS 10.3 and 12.1) [Mapbox-iOS-SDK license](https://github.com/mapbox/mapbox-gl-native-ios/blob/master/LICENSE.md) not visible in settings. However scroll view scrolls vertically a lot as if the text is visible actually. When copy paste it to txt file and load it manually from file set in license_plist.yml it is invisible too. In iOS 13 it is displayed ok if not crashing settings app.

Perhaps there are some illegal characters in the text? Maybe texts should be preparsed escaping such a characters?

**Comment by illabo** [comment]
I've tried running my app on even older device. On iPhone 4s with iOS 9.3.6 all the licenses are offset one screen height from top. However Mapbox-iOS-SDK license is visible! Thinking I was wrong not to scroll it on iOS 10—12 all way down, maybe it's just offset too. But no.

<img src="https://user-images.githubusercontent.com/6376785/89879262-029d5000-dc06-11ea-8239-086e3e1dd164.png" width=30% height=30%> <img src="https://user-images.githubusercontent.com/6376785/89879272-06c96d80-dc06-11ea-8f9c-1cd39f5331c0.png" width=30% height=30%>

All the licenses are visible ok, except Mapbox's. And it isn't offset as on iOS 9.

**Comment by Cyberbeni** [comment]
Maybe it is too long. What happens if you split it into smaller chunks, can all of them render?

**Comment by illabo** [comment]
Thanks for suggestion. Maybe it’s length is the reason however other quite long texts are visible ok. 
Haven’t tried splitting as it is against of idea of licenses convenient presentation.

**Comment by Cyberbeni** [comment]
I mean [we are jamming all the text into one footer](https://github.com/mono0926/LicensePlist/blob/40203c787cc7d8920420bd5079dd86360493a7f0/Sources/LicensePlistCore/Entity/LicensePlistHolder.swift#L20), which probably uses a UILabel, which doesn't care about not showing all its content inside the tableview's scrollview, so it tries to render all the text at once. We could try splitting up the paragraphs and use separate elements for them if that is the cause of the problem.

**Comment by Cyberbeni** [comment]
@illabo could you try my version from here? https://github.com/Cyberbeni/LicensePlist/tree/multiple-footers

It splits double newlines to different footers, which results in a slightly bigger gap between them but if it solves the issue then I think that's acceptable.

I initially also converted single newlines to spaces but then I realised maybe not all licences in markdown, so I'll leave that for another issue.

**Comment by Cyberbeni** [comment]
It works on iOS 10.3 simulator
The gaps are way bigger on iOS14, might be better to split on horizontal lines.

**Comment by illabo** [comment]
@Cyberbeni Sorry, I haven’t checked your fork yet. The issue is only present in older iOS versions. Starting with iOS 13 everything looks great. Maybe it’s better to check iOS version before splitting the long text?
Sorry again, I definitely have to take a look at your version.
