### ISSUE TITLE
Consider using the official swift-argument-parser

### ISSUE THREAD

**Issue by Cyberbeni** [mono0926/LicensePlist#141]
The currently used library doesn't seem to be designed to have a lot of parameters: https://github.com/mono0926/LicensePlist/blob/40203c787cc7d8920420bd5079dd86360493a7f0/Sources/LicensePlist/main.swift#L28

The [official argument parser](https://github.com/apple/swift-argument-parser) handles input declaration in a more readable way. And it also supports [generating a completion script](https://github.com/apple/swift-argument-parser/blob/main/Documentation/07%20Completion%20Scripts.md).

Let me know if you want to switch and I'll make a PR.

**Comment by mono0926** [comment]
> Let me know if you want to switch and I'll make a PR.

Thanks, please make a PR 🙏
