### ISSUE TITLE
How can I get the html file ?

### ISSUE THREAD

**Issue by LearnWithTung** [mono0926/LicensePlist#143]
According to this document: https://qiita.com/satoru_pripara/items/968b88a4cf55a046f3ba
I want to display the license inside the app so I add the script to Xcode run phase 
`LICENSE_OUTPUT_FILE="${PROJECT_NAME}/Licenses/license.html"
if which license-plist >/dev/null; then
license-plist --output-path "LicensePlistOutput" --html-path $LICENSE_OUTPUT_FILE
fi
`
But I don't know how and where to get the html file 
Please help me

**Comment by mono0926** [comment]
It works naturally.

```
license-plist --html-path license.html
cat license.html
```

If the log says this, you can execute again with `--force` flag as written. 

```
[2020-10-15T16:50:34.587+09:00] [WARNING] Completed because no diff. You can execute force by `--force` flag.
```

**Comment by LearnWithTung** [comment]
I can't find the html file in any place
