### ISSUE TITLE
Package.resolved not found when using Xcode workspaces.

### ISSUE THREAD

**Issue by orj** [mono0926/LicensePlist#165]
My project structure is similar to this:

```
Application.xcworkspace
Applications/Application.xcodeproj
Applications/Application/Sources
Modules/Package.swift
Modules/Package1/Sources
Modules/Package2/Sources
Modules/Package3/Sources
```

The `xcworkspace` includes the `Applications` project which has all my App & Extension targets and those targets depend on modules defined in the `Modules` package which is also in the workspace. Those modules have dependencies on open source packages.

Xcode works fine with this dependency structure and writes the the `Package.resolved` file into `Application.xcworkspace/xcshareddata/swiftpm/Package.resolved `.

LicensePlist can't seem to find this `Package.resolved` file.  I've tried various command-line options.  It seems to me given that LicensePlist ultimately just wants to be told where the `.resolved` file is, that there should be a command-line argument that just gives it a `.resolved` file. I'm smart enough to work out where this file exists. But instead LicensePlist makes assumptions about project structure and tries to help me out but because its assumptions are wrong I can't get it to work.

I'm happy to provide a patch to make this work.  Perhaps even a --workspace-path option that allows you to point LicensePlist at a workspace that might include a Package.resolved file. But I still think that is more prone to error than just pointing it directly at the `Package.resolved` file.

**Comment by kpmaalej** [comment]
Hi @orj 

My project structure is similar to yours. I have: 

```
Application.xcworkspace
App/Application.xcodeproj
App/Application
Modules/
Modules/Package1/Package.swift 
Modules/Package1/Sources
Modules/Package2/Package.swift 
Modules/Package2/Sources
```

The Application project depends on each package listed in the `Modules` directory. 

I use a version of license-plist that includes the `--xcworkspace-path` option. 

The command I invoke is `"${SRCROOT}/../Tools/bin/license-plist" --suppress-opening-directory --add-version-numbers --pods-path "${SRCROOT}/../Pods" --xcworkspace-path "${SRCROOT}/../*.xcworkspace" --output-path "${SRCROOT}/Application/Supporting Files/Settings.bundle"` 

Yet I see in the build log that it fails to find the Package.resolved file at the specified place: 
```
[WARNING] Not found: Package.resolved -- file:///[...]/Repository/App/.
[WARNING] Not found: Package.swift -- file:///[...]/Repository/App/.
[INFO] Swift Package Manager License collect start
```

Would you have an idea why that is, and I could do to fix it?
