### ISSUE TITLE
Combine --single-page with --add-version-numbers

### ISSUE THREAD

**Issue by blg-nb** [mono0926/LicensePlist#170]
Hello,

why is it not possible to combine the "--single-page" option with the "--add-version-numbers" option?

It would be great if you could combine that, if it were somehow possible.

**Comment by mono0926** [comment]
Hi.

> why is it not possible to combine the "--single-page" option with the "--add-version-numbers" option?

Not intended.

> It would be great if you could combine that, if it were somehow possible.

I haven't had time for a while, I'm welcoming the pull request 🐶

**Comment by blg-nb** [comment]
I have made a pull request for you :)
