### ISSUE TITLE
Binary downloaded from Github release assets not up to date

### ISSUE THREAD

**Issue by mathaeus** [mono0926/LicensePlist#180]
The binary that I downloaded from the release page for `3.19.1` is actually the `3.14.1` binary.
Same for `3.19.0`.

I built the binary now myself, that gives me the correct one (as expected).

**Comment by mono0926** [comment]
@mathaeus 

Thanks, fixed now and released [3.19.2](https://github.com/mono0926/LicensePlist/releases/tag/3.19.2) 👌
