### ISSUE TITLE
Could not find License for immobiliare/RealHTTP

### ISSUE THREAD

**Issue by ChaosCoder** [mono0926/LicensePlist#206]
I'm using LicensePlist successfully for all my dependencies via SPM. I recently added a new library [RealHTTP](https://github.com/immobiliare/RealHTTP) and LicensePlist fails to find the LICENSE but I do not see any difference in how.

Dependency via SPM
```
https://github.com/immobiliare/RealHTTP.git
```

The following output is produced when executing `license-plist` without any parameters:
```
[...]
[2023-01-16T10:16:33.200+01:00] [WARNING] 404 error, license download failed(owner: immobiliare, name: RealHTTP), so finding parent...
[2023-01-16T10:16:33.403+01:00] [WARNING] RealHTTP's original and parent's license not found on GitHub
[2023-01-16T10:16:33.405+01:00] [INFO] Directory created: com.mono0926.LicensePlist.Output -- file:///Users/ChaosCoder/Example/
[2023-01-16T10:16:33.411+01:00] [INFO] End
[2023-01-16T10:16:33.411+01:00] [INFO] ----------Result-----------
[2023-01-16T10:16:33.411+01:00] [INFO] # Missing license:
[2023-01-16T10:16:33.411+01:00] [WARNING] RealHTTP
```

So the problem is either RealHTTP or LicensePlist. I am using LicensePlist version `3.23.4`.

**Comment by acevif** [comment]
@ChaosCoder 
Please add its license by hand via the [YAML config file](https://github.com/mono0926/LicensePlist/blob/master/Tests/LicensePlistTests/Resources/license_plist.yml).

I could reproduce the issue. 
I traced the cause of it but I noticed there is no quick solution so far.

RealHTTP has changed its license from Apache License to MIT License. 
(see: https://github.com/immobiliare/RealHTTP/commits/main/LICENSE)

This results in its repository having multiple licenses.
I think GitHub's license API returns the 404 not found error helplessly.

LicensePlist uses GitHub's license API, and the API doesn't accept any version specification.
So it is a limitation of LicensePlist so far.

**Comment by ChaosCoder** [comment]
Thank you, that worked! 

However, I opened a GitHub support ticket because of this 404 response. They already replied and ran their job on that particular repository to update their database. Now, the proper license is returned via the API and thus LicensePlist works with that repo flawlessly. So now I do not even need the manual entry. 👍🏻
