### ISSUE TITLE
`LicensePlist (3.24.8)`, which does not support `iOS`

### ISSUE THREAD

**Issue by wata** [mono0926/LicensePlist#216]
I tried to upgrade from 3.24.5 to 3.24.8 with `pod update` and got the following error

> [!] The platform of the target `XXX` (iOS 15.0) is not compatible with `LicensePlist (3.24.8)`, which does not support `iOS`.

Maybe need to add `s.ios.deployment_target = 'XXX'` to podspec?

https://github.com/mono0926/LicensePlist/compare/3.24.8...main#diff-4e96489b6a967fc179c2d53ccfb81d2ca59128d71b4d86183d7717f10ba055c6R11

**Comment by mono0926** [comment]
@wata 

Sorry, fixed now: https://github.com/mono0926/LicensePlist/releases/tag/3.24.9

**Comment by wata** [comment]
@mono0926 Thanks for the very quick fix. It's working fine 👍
