### ISSUE TITLE
Privacy manifest required by Apple 

### ISSUE THREAD

**Issue by wenfeng-duan** [mono0926/LicensePlist#226]
Hi team,

Starting with Spring 2024 Apple requires third-party SDKs to add a Privacy Manifest file.
Apple has explicitly mentioned Reachability as one of the third party SDKs that must include a privacy manifest otherwise any App that includes it is not allowed to release an update (or new app) to the store.

Is there any plans to add a privacy manifest?

https://developer.apple.com/support/third-party-SDK-requirements/
https://developer.apple.com/documentation/bundleresources/privacy_manifest_files

Thanks,
Duan

**Comment by mono0926** [comment]
This tool is not bundled in the app, it just generates plist files, so Privacy Manifest file support should not be necessary.
