### ISSUE TITLE
Exclude libraries using regex

### ISSUE THREAD

**Issue by Sherlouk** [mono0926/LicensePlist#28]
Currently the excluded libraries from the Config are checked with a strict 'contains' check. [Here](https://github.com/mono0926/LicensePlist/blob/5bce47922c4eb3d57fa1664ad1405d07a67fedc7/Sources/LicensePlistCore/LicensePlist.swift#L40).

It would be pretty handy if this could also take a regex, for example: `/^Core.*$/` would exclude anything which started with "Core" - potentially useful for internal frameworks.

**Comment by mono0926** [comment]
@Sherlouk 

Thanks for the feedback.
I'll try it 👍

**Comment by mono0926** [comment]
@Sherlouk 

I [implemented](https://github.com/mono0926/LicensePlist/issues/34) and merged to master.

Could you try it?
Regex expression sample is here: https://github.com/mono0926/LicensePlist/blob/master/Tests/LicensePlistTests/Resources/license_plist.yml#L9 .

I  adopted your proposal as it is 👍

**Comment by Sherlouk** [comment]
@mono0926 

Woah super fast! I'll be sure to give it a test now, cheers!

**Comment by Sherlouk** [comment]
Working fine for me! Thanks! Closing the issue
