### ISSUE TITLE
Plist not in correct format error if license contain special characters

### ISSUE THREAD

**Issue by xuaninbox** [mono0926/LicensePlist#42]
If the license contain special characters, such as 

Hero - https://github.com/lkzhao/Hero/blob/master/LICENSE
- which has /<me@lkzhao.com/>

CryptoSwift - https://github.com/krzyzanowskim/CryptoSwift/blob/master/LICENSE 
- which has /<marcin.krzyzanowski@gmail.com/>

will cause the the generated Hero.plist and CryptoSwift.plist not in correct format

**Comment by mono0926** [comment]
@xuaninbox 

Thanks for the report.

[I fixed it](https://github.com/mono0926/LicensePlist/issues/43) and merged to `master`.
Could you check it?

**Comment by xuaninbox** [comment]
Yep it works great!

however I did see one dev did escaped the license so it got escaped again - https://github.com/Skyscanner/SkyFloatingLabelTextField/blob/master/LICENSE.md

but its pretty rare

**Comment by mono0926** [comment]
@xuaninbox 

Thanks.

> however I did see one dev did escaped the license so it got escaped again -

I [tried to fix it](https://github.com/mono0926/LicensePlist/issues/44), but I noticed that this original file is weird, isn't it?

https://raw.githubusercontent.com/Skyscanner/SkyFloatingLabelTextField/master/LICENSE.md
`_&lt;<http://www.apache.org/licenses/>&gt;_`

So, I maybe cannot handle it.

**Comment by mono0926** [comment]
@xuaninbox 

May I close the issue?

And I have to tell you that [I changed the generating plist files implementation by using PropertyListSerialization](https://github.com/mono0926/LicensePlist/pull/49).

The generated files has changed a bit,  but those changes are only escaping logic difference, so no problem I think.

**Comment by xuaninbox** [comment]
Sry yes!
