### ISSUE TITLE
A terminal window is launched when run by xcode

### ISSUE THREAD

**Issue by combinatorial** [mono0926/LicensePlist#50]
When licenseplist is run by xcode it launches a terminal window in the Settings.bundle directory. Is it possible to stop this window from appearing?

I am running as a build action...

    cd $SRCROOT
    license-plist --output-path Settings.bundle

**Comment by mono0926** [comment]
@combinatorial 

Only when the files are created or updated, the terminal or the finder opens.
It is intended behavior(https://github.com/mono0926/LicensePlist/blob/4f353d30729fa388d908ee78745d8db19bd1749a/Sources/LicensePlistCore/LicensePlist.swift#L21), but I can add an option to suppress that(`--suppress-opening-directory`).

> Only when the files are created or updated

If you run the command second time, no terminals open.
Nevertheless, you can suppress the behavior, I'll add the option.

**Comment by combinatorial** [comment]
That would be great to add that option, thank you! Though I am confused by the addition of the wontfix label?

**Comment by mono0926** [comment]
@combinatorial 

> That would be great to add that option, thank you!

Okay, it's easy, so I'll work on shortly 👍

**Comment by mono0926** [comment]
@combinatorial 

I supported `--suppress-opening-directory` flag and released https://github.com/mono0926/LicensePlist/releases/tag/1.4.0 .

If you use Homebrew, you can upgrade the LicensePlist by `brew upgrade license-plist`.
And try this:

```sh
cd $SRCROOT
license-plist --output-path Settings.bundle --suppress-opening-directory
```

If it is okay, close the issue please.

**Comment by combinatorial** [comment]
That works, thank you so much, I appreciate the fast turnaround.
