### ISSUE TITLE
xcode 8.3 mandatory ?

### ISSUE THREAD

**Issue by tirrorex** [mono0926/LicensePlist#55]
Why is xcode 8.3 mandatory for homebrew installation?
I assume this has to do with specific commands used by the tool?
Is there any way to use this with xcode 8.2.1 or will i have to upgrade?

**Comment by mono0926** [comment]
Sorry, I haven't supported [Bottles](https://github.com/Homebrew/brew/blob/master/docs/Bottles.md) of Homebrew, so you have to build the sources to install the tool via Homebrew.
And the library needs Xcode 8.3 to be built.

You can install the tool by downloading from [Releases](https://github.com/mono0926/LicensePlist/releases).

I created the issue: [Support Homebrew Bottles · Issue #56](https://github.com/mono0926/LicensePlist/issues/56).
If this is supported your wish will be fulfilled.

**Comment by tirrorex** [comment]
Okay so this will have to wait a few weeks, we are still using swift 2.3 and don't have the time to change version at the moment.
Thanks for the answer

**Comment by mono0926** [comment]
> Okay so this will have to wait a few weeks, we are still using swift 2.3 and don't have the time to change version at the moment.

I'll try it.

Currently, you may be able to install the tool by this method:

> You can install the tool by downloading from [Releases](https://github.com/mono0926/LicensePlist/releases).

**Comment by mono0926** [comment]
@tirrorex 

> we are still using swift 2.3 and don't have the time to change version at the moment.

And, LicensePlist is only a tool, not a framework, so even if your project is using Swift 2.3, you can introduce LicensePlist.

**Comment by tirrorex** [comment]
Good to know, thanks
