### ISSUE TITLE
Cannot install by `brew install license-plist` on Xcode 9 / High Sierra (currently beta)

### ISSUE THREAD

**Issue by mono0926** [mono0926/LicensePlist#71]
Cannot install by `brew install license-plist` on Xcode 9 / High Sierra (currently beta).

```sh
➜  ~ brew install license-plist                                           
==> Installing license-plist from mono0926/license-plist
==> Downloading https://github.com/mono0926/LicensePlist/archive/1.6.0.tar.gz
==> Downloading from https://codeload.github.com/mono0926/LicensePlist/tar.gz/1.6.0
######################################################################## 100.0%
==> make install PREFIX=/usr/local/Cellar/license-plist/1.6.0
Last 15 lines from /Users/mono/Library/Logs/Homebrew/license-plist/01.make:
2017-08-18 12:29:25 +0900

make
install
PREFIX=/usr/local/Cellar/license-plist/1.6.0

swift build -c release -Xswiftc -static-stdlib
error: manifest parse error(s):
sandbox-exec: sandbox_apply_container: Operation not permitted
make: *** [build] Error 1
```

`error: manifest parse error(s):` is weird.

`make build`(`swift build -c release -Xswiftc -static-stdlib`) command succeeds, so I cannot figured out how to resolve this issue 🤔

**Comment by yonaskolb** [comment]
We just had this issue in https://github.com/yonaskolb/XcodeGen as well. Not sure what's causing the problem but passing `--no-sandbox` to brew install seemed to fixed it

**Comment by mono0926** [comment]
@yonaskolb 

> passing --no-sandbox to brew install seemed to fixed it

Thanks, the issue fixed well 👍 

I updated README:
https://github.com/mono0926/LicensePlist/blob/master/README.md#%EF%B8%8F-for-high-sierra-betagm-candidate

High Sierra will be released officially on September 26th, so I'll check whether `--no-sandbox` is not needed for the official version.

---

- [ ] Check whether `--no-sandbox` is not needed for the official version.

**Comment by hernangonzalez** [comment]
Looks like it is still needed.

**Comment by yonaskolb** [comment]
As an update we fixed this in XcodeGen by adding `--disable-sandbox` to swift build. You don't need to add `--no-sandbox` to brew install for that either
eg
```
swift build --disable-sandbox -c release -Xswiftc -static-stdlib
```

**Comment by mono0926** [comment]
@yonaskolb 

> As an update we fixed this in XcodeGen by adding `--disable-sandbox` to swift build. You don't need to add `--no-sandbox` to brew install for that either

Thanks, it works fine 👍 
I've released https://github.com/mono0926/LicensePlist/releases/tag/1.7.2
