### ISSUE TITLE
Brew installation error 1.6.1

### ISSUE THREAD

**Issue by xuaninbox** [mono0926/LicensePlist#72]
Resolving https://github.com/kylef/Commander.git at 0.6.1
Compile Swift Module 'Yaml' (6 sources)
Compile Swift Module 'Spectre' (8 sources)
Compile Swift Module 'Result' (2 sources)
Compile Swift Module 'LoggerAPI' (1 sources)
Compile Swift Module 'Himotoki' (11 sources)
Compile Swift Module 'HeliumLogger' (2 sources)
Compile Swift Module 'APIKit' (22 sources)
Compile Swift Module 'Commander' (9 sources)
Compile Swift Module 'LicensePlistCore' (23 sources)
Compile Swift Module 'LicensePlist' (1 sources)
Linking ./.build/release/LicensePlist
cp -f ".build/release/LicensePlist" "/usr/local/Cellar/license-plist/1.6.1/bin/license-plist"
cp: /usr/local/Cellar/license-plist/1.6.1/bin/license-plist: No such file or directory
make: *** [install] Error 1

seems to be caused by this 2e3abcc

**Comment by mono0926** [comment]
@xuaninbox 

Sorry I tried to fix https://github.com/mono0926/LicensePlist/issues/71, but It broke brew installation.
I reverted https://github.com/mono0926/LicensePlist/commit/2e3abcc605107d89d5b0a2da77e71a9df8018877 and released 1..6.2.

**Comment by xuaninbox** [comment]
All good! Awesome tool!! 👍
