### ISSUE TITLE
Support for manually entering license

### ISSUE THREAD

**Issue by leetal** [mono0926/LicensePlist#74]
Hi! 
Is there any support for adding license information manually, for example in the configuration file or from a standalone plist-file?

I want to include third-party licences that is not in cocoapods or carthage.

**Comment by Sherlouk** [comment]
Are these third-parties on GitHub by chance? If so you can specify repositories with licenses and they'll be included also!

**Comment by mono0926** [comment]
@leetal 

> Is there any support for adding license information manually, for example in the configuration file or from a standalone plist-file?

You can specify it by the config file.
See here: https://github.com/mono0926/LicensePlist/blob/master/README.md#--config-path

Config file example: https://github.com/mono0926/LicensePlist/blob/master/Tests/LicensePlistTests/Resources/license_plist.yml

**Comment by mono0926** [comment]
@leetal 

Other than GitHub repository which has LICENSE file, I'm considering to add license body option to config file( https://github.com/mono0926/LicensePlist/issues/23 ).

**Comment by leetal** [comment]
@mono0926 manually entering a body is what i'm after, since we have a lot of third-party licences which are not on github at the moment.

**Comment by mono0926** [comment]
@leetal 
Okay, thanks for the feedback 👍 
I'll treat this issue at https://github.com/mono0926/LicensePlist/issues/23 , so I close this.
