### ISSUE TITLE
Run Script can also be placed at at Project Build Phases

### ISSUE THREAD

**Issue by hstdt** [mono0926/LicensePlist#78]
![image](https://user-images.githubusercontent.com/10215098/31944619-485995e4-b892-11e7-95d9-1504de6d0a67.png)

**Comment by mono0926** [comment]
@hstdt 

Thanks, it works fine and I think it is better than running at `Build Pre-actions`.
(At that time, I misunderstood about that for some reason.)

[I updated README 👍](https://github.com/mono0926/LicensePlist/commit/b9ad26e301c2fce452ec1a13218e55f98b8a4659)

**Comment by hstdt** [comment]
@mono0926 

`cd $SRCROOT`  at run script will lead to building error.(Build will be success)

**Comment by mono0926** [comment]
@hstdt 

Thanks, `cd $SRCROOT` didn't lead to building error for my project, but it is unnecessary, so [I deleted it 👍](https://github.com/mono0926/LicensePlist/commit/df04004420dc63db1dbb2354067813e84f0a384c)
