### ISSUE TITLE
LICENSE.txt files on GitHub are not recognized 

### ISSUE THREAD

**Issue by MrAlek** [mono0926/LicensePlist#80]
Some repositories have a file extension on their license files (`.txt` or `.md`), such as https://github.com/SVProgressHUD/SVProgressHUD . Currently, those licenses aren't picked up by LicensePlist and end up in the "Missing license" list. Would be great to be able to include those license files as well.

**Comment by mono0926** [comment]
Thanks for the feedback.

[GitHub license API](https://developer.github.com/v3/licenses/#get-a-repositorys-license) is used when collecting Carthage library licenses.

```sh
curl "https://api.github.com/repos/SVProgressHUD/SVProgressHUD/license"
```

The result is here.

```json
"license": {
    "key": "other",
    "name": "Other",
    "spdx_id": null,
    "url": null,
    "featured": false
  }
```

I think it is better to send the pull request to the library to can be get the license via API.
For now, [you can also specify the license body manually](https://github.com/mono0926/LicensePlist/blob/cf50da0080d6629ec2e1e01bf31bb83e7e86cbbc/Tests/LicensePlistTests/Resources/license_plist.yml#L12-L41).

**Comment by MrAlek** [comment]
Thanks for the super quick reply! I'll send some PRs :)
