### ISSUE TITLE
Why github api needed?

### ISSUE THREAD

**Issue by mlfarrell** [mono0926/LicensePlist#82]
Is there a version of this app that doesn't hit the github APIs at all?  I'd like to avoid having to deal with api limits and tokens, and just have it crawl the bundles for existing local licenses like cocoapods does.

**Comment by mono0926** [comment]
It's my software design decision.
Indeed it is possible to crawl the licenses, but I think using GitHub API is more robust than it.

You can fork and modify to crawl the licenses, but I cannot merge that kind of change.
