### ISSUE TITLE
latest_result.txt is different on different macs

### ISSUE THREAD

**Issue by xuaninbox** [mono0926/LicensePlist#83]
https://github.com/mono0926/LicensePlist/blob/ccf5d5b9c755e417d4c31382fc27c75943070899/Sources/LicensePlistCore/Entity/PlistInfo.swift#L48

.map will generate the lists in different order, maybe sort after map?

**Comment by mono0926** [comment]
@xuaninbox 

`.map` will keep orders, but `cocoaPodsLicenses` order may be different on different mac.
So, I [added `sorted()` before `.map`](https://github.com/mono0926/LicensePlist/pull/84), and released 1.8.3.
Could you confirm the result is same with different macs?
