### ISSUE TITLE
Integrate into main homebrew repository

### ISSUE THREAD

**Issue by sgleadow** [mono0926/LicensePlist#88]
This is a great little tool, thanks for the effort.

I noticed the homebrew installation is via a tap, would you consider adding the formula to the main homebrew repository?

I assume they generally want the formulas added by the maintainer where possible, but otherwise, I can try and send a PR for that.

Or have you already considered that and decided it's not what you want?

**Comment by mono0926** [comment]
Thanks for the feedback 👍 

I think It is better adding formula to the main homebrew repository, but I'm not familiar with Homebrew distribution.

>  I can try and send a PR for that.

So, I'm welcome your PR 😄 

---

FYI, current release flow is this:

1. Execute this: `./release.sh X.Y.Z GITHUB_AUTH_TOKEN`
    - release.sh: https://github.com/mono0926/LicensePlist/blob/master/release.sh
2. Homebrew installation via a tap is updated here: https://github.com/mono0926/LicensePlist/blob/6ca6b47cfa3c0ead6236613303fe84e705550a92/release.sh#L22-L41
