### ISSUE TITLE
Close terminal window after generation 

### ISSUE THREAD

**Issue by Przemyslaw-Wosko** [mono0926/LicensePlist#91]
Just as on this gif form readme, once we run generation process, new terminal window is opened. In case CI runs job for each commit, new terminal window appear. 

1) do we have to open new window terminal? 
2) is there a way to close this window after process completion? 

https://github.com/mono0926/Resource/raw/master/LicensePlist/LicensePlist.gif

**Comment by mono0926** [comment]
You can suppress opening terminal by `--suppress-opening-directory` flag.
https://github.com/mono0926/LicensePlist#--suppress-opening-directory

See also this: https://github.com/mono0926/LicensePlist/issues/50

**Comment by Przemyslaw-Wosko** [comment]
@mono0926 thanks for response!
